name: trainit
description: A new Flutter project.
version: 1.0.0+0

publish_to: 'none'

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: 0.19.0
  uuid: 3.0.7
  flutter_launcher_icons: '^0.13.1'
  flutter_bloc: "8.1.2"
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.7
  flutter_svg: ^2.0.5
  get_it: ^7.3.0
  http: ^1.1.0
  logger: ^1.3.0
  event_bus: ^2.0.0
  instant: ^0.5.1
  path_provider: ^2.0.15
  image_picker: ^0.8.7+5
  flutter_image_compress: ^2.0.3
  http_parser: ^4.0.2
  image: ^4.1.3
  cached_network_image: ^3.3.0
  package_info_plus: ^4.0.2
  url_launcher: ^6.1.11
  material_symbols_icons: ^4.2668.0
  symbols: ^0.0.0
  flutter_signin_button: ^2.0.0
  loading_animation_widget: ^1.2.0+4
  flutter_keyboard_visibility: ^5.4.1
  fluttertoast: ^8.2.2
  lottie: ^2.7.0
  share_plus: ^7.2.1
  # Firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0
  google_sign_in: ^6.1.4
  firebase_crashlytics: ^3.3.5
  firebase_analytics: ^10.4.5
  firebase_performance: ^0.9.2+5
  path: ^1.8.2
  sqflite: ^2.2.8
  objectbox: ^2.0.0
  objectbox_flutter_libs: ^2.0.0
  shared_preferences: ^2.1.0
  flutter_localizations:
    sdk: flutter
  flutter_localization: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  objectbox_generator: any
  bloc_test: ^9.1.1
  mocktail: ^0.3.0
  mockito: ^5.4.2

flutter_icons:
  android: true  
  ios: true  
  image_path: "assets/launcher_icon.png"
  adaptive_icon_background: "assets/launcher_icon_background.png"  
  adaptive_icon_foreground: "assets/launcher_icon_foreground.png"
  remove_alpha_ios: true
flutter:
  assets:
    - assets/
  generate: true
  uses-material-design: true
