import 'package:intl/intl.dart' as intl;

import 'app_localizations.dart';

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get tomorrow => 'Tomorrow:';

  @override
  String get today_trainings => 'Trainings:';

  @override
  String get monday => 'Monday';

  @override
  String get tuesday => 'Tuesday';

  @override
  String get wednesday => 'Wednesday';

  @override
  String get thursday => 'Thursday';

  @override
  String get friday => 'Friday';

  @override
  String get saturday => 'Saturday';

  @override
  String get sunday => 'Sunday';

  @override
  String get today => 'Today';

  @override
  String get move => 'Move';

  @override
  String today_collapsed(num count) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
      
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: 'Today: $countString Trainings',
      one: 'Today: 1 Training',
      zero: 'Today: 0 Trainings',
    );
    return '$_temp0';
  }

  @override
  String exercise_not_valid(String name) {
    return 'Exercise \'$name\' is not valid';
  }

  @override
  String exercises(num count) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
      
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Exercises',
      one: '1 Exercise',
      zero: '0 Exercises',
    );
    return '$_temp0';
  }

  @override
  String exercises_label(num count) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
      
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: 'Exercises: $countString',
      zero: 'Exercises: ',
    );
    return '$_temp0';
  }

  @override
  String training_title(String name) {
    return 'Training - $name';
  }

  @override
  String trainings(num count) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
      
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Trainings',
      one: '1 Training',
      zero: 'No Trainings',
    );
    return '$_temp0';
  }

  @override
  String minutes_long(num count) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
      
    );
    final String countString = countNumberFormat.format(count);

    return '$countString minutes';
  }

  @override
  String minutes_short(num count) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
      
    );
    final String countString = countNumberFormat.format(count);

    return '$countString min';
  }

  @override
  String get sets_label => 'Sets:';

  @override
  String get rest_day => 'Rest-day';

  @override
  String get calendar_title => 'Calendar';

  @override
  String get help => 'Help';

  @override
  String get calendar_help_1_title => 'Introduction';

  @override
  String get calendar_help_1_message => 'The calendar section is to provide you a detailed overview on you upcoming trainings. Your calendar will be automatically generated by your training plan.';

  @override
  String get calendar_help_2_title => 'Trainings';

  @override
  String get calendar_help_2_message => 'All of your trainings for the upcoming week will be shown to you. As summary, you can see the name, number of exercises and the calculated time you will probably need to complete the training.';

  @override
  String get calendar_help_3_title => 'Detailed information';

  @override
  String get calendar_help_3_message => 'You can see a detailed version of your training by clicking on it.';

  @override
  String get delete => 'Delete';

  @override
  String get update => 'Update';

  @override
  String days_ago(num count) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
      
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString days ago',
      one: '1 day ago',
      zero: 'today',
    );
    return '$_temp0';
  }

  @override
  String get pounds => 'lbs';

  @override
  String get kilograms => 'kg';

  @override
  String get minutes => 'min';

  @override
  String get seconds => 's';

  @override
  String get meters => 'm';

  @override
  String get centimeters => 'cm';

  @override
  String get statistics_title => 'Statistics';

  @override
  String get your_personal_records_label => 'Personal Records:';

  @override
  String get your_goals_label => 'Goals:';

  @override
  String get personal_record_label => 'Personal Record:';

  @override
  String get value_name_label => 'Value Name:';

  @override
  String get personal_record => 'Personal Record';

  @override
  String get body_value => 'Body Value';

  @override
  String get body_weight => 'Body Weight';

  @override
  String get body_fat => 'Body Fat';

  @override
  String get create_goal_title => 'Create Goal';

  @override
  String get edit_personal_record_title => 'Edit Personal Record';

  @override
  String get create_personal_record_title => 'Create Personal Record';

  @override
  String get name_label => 'Name:';

  @override
  String get type_label => 'Type:';

  @override
  String get value_label => 'Value:';

  @override
  String get weight => 'Weight';

  @override
  String get distance => 'Distance';

  @override
  String get time => 'Time';

  @override
  String get name_placeholder => 'Enter a name';

  @override
  String get empty_personal_records_title => 'Nothing to see in here.';

  @override
  String get empty_personal_records_message => 'Start by creating a new Personal Record to trace your progress.';

  @override
  String get delete_personal_record_title => 'Delete Personal Record.';

  @override
  String delete_personal_record_message(String name) {
    return 'Do you really want to delete your Personal Record $name. The removal cannot be reverted.';
  }

  @override
  String get superset => 'Superset';

  @override
  String get delete_superset => 'Unlink Superset';

  @override
  String get yes => 'Yes';

  @override
  String get no => 'No';

  @override
  String get save => 'Save';

  @override
  String get enter_name => 'Name cannot be empty';

  @override
  String get enter_text => 'Value cannot be empty';

  @override
  String value_between(num from, num to) {
    final intl.NumberFormat fromNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
      
    );
    final String fromString = fromNumberFormat.format(from);
    final intl.NumberFormat toNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
      
    );
    final String toString = toNumberFormat.format(to);

    return 'Value must be between $fromString and $toString';
  }

  @override
  String get statistics_help_1_title => 'Introduction';

  @override
  String get statistics_help_1_message => 'Here, you can manage your personal records, you hit over the time.';

  @override
  String get statistics_help_2_title => 'Creating a new personal record';

  @override
  String get statistics_help_2_message => 'To create a new personal record category just click the +-button in the bottom-right corner of the page, provide a name and the weight you liftet and click on \'Save\'.';

  @override
  String get statistics_help_3_title => 'Editing Personal Records';

  @override
  String get statistics_help_3_message => 'By clicking on your personal record and selecting \'Update\', you can edit your personal record and add a new weight to it.';

  @override
  String get defaults_label => 'Defaults';

  @override
  String get weightunit_label => 'Weight Unit';

  @override
  String get set_duration_label => 'Set duration';

  @override
  String get set_rest_duration_label => 'Rest duration';

  @override
  String get training_plan_label => 'Training Plan';

  @override
  String get friends_label => 'Friends';

  @override
  String get all_friends_label => 'All friends';

  @override
  String get notification_friends_label => 'New Notifications';

  @override
  String get requested_friends_label => 'Requests';

  @override
  String get added_friends_label => 'Added';

  @override
  String get add_friends => 'Add friends';

  @override
  String get following => 'Following';

  @override
  String get followers => 'Followers';

  @override
  String get no_friends => 'You don’t have any friends added.';

  @override
  String get accept => 'Accept';

  @override
  String get lets_fix_friends => 'Let\'s fix that';

  @override
  String get view_friends => 'View friends';

  @override
  String get friends_title => 'Your friends';

  @override
  String get view => 'View';

  @override
  String get goal => 'Goal';

  @override
  String get featured_personal_records => 'Featured Personal Records';

  @override
  String get profile => 'Profile';

  @override
  String friends(num count) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
      
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString friends',
      one: '1 friend',
    );
    return '$_temp0';
  }

  @override
  String follower_number(num count) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
      
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Followers',
      one: '1 Follower',
    );
    return '$_temp0';
  }

  @override
  String following_number(num count) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
      
    );
    final String countString = countNumberFormat.format(count);

    return '$countString Following';
  }

  @override
  String follower_text(num count) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
      
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString days',
      one: 'yesterday',
      zero: 'today',
    );
    return 'Follower since $_temp0';
  }

  @override
  String following_text(num count) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
      
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString days',
      one: 'yesterday',
      zero: 'today',
    );
    return 'Following since $_temp0';
  }

  @override
  String get account_title => 'Account';

  @override
  String get settings_title => 'Settings';

  @override
  String get design_label => 'Design:';

  @override
  String get theme_label => 'App Theme:';

  @override
  String get theme_light => 'Light';

  @override
  String get theme_dark => 'Dark';

  @override
  String get theme_system => 'System';

  @override
  String get documents_label => 'Documents:';

  @override
  String get terms_label => 'Terms of Service';

  @override
  String get privacy_label => 'Privacy Policy';

  @override
  String get view_browser => 'View in browser';

  @override
  String get contact_label => 'Contact:';

  @override
  String get email_label => 'Email';

  @override
  String get account_label => 'Account:';

  @override
  String get username_label => 'Username';

  @override
  String get sign_out => 'Sign Out';

  @override
  String get about_label => 'About:';

  @override
  String get version_label => 'Version';

  @override
  String get edit => 'Edit';

  @override
  String get days_label => 'Trainings:';

  @override
  String get add_new => 'Add new';

  @override
  String get add_new_exercise => 'Add new Exercise';

  @override
  String number_sets_label(num count) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
      
    );
    final String countString = countNumberFormat.format(count);

    return 'Number of Sets: $countString';
  }

  @override
  String number_sets_short(num count) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
      
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$countString Sets',
      one: '1 Set',
      zero: '0 Sets',
    );
    return '$_temp0';
  }

  @override
  String set_label(num count) {
    final intl.NumberFormat countNumberFormat = intl.NumberFormat.compact(
      locale: localeName,
      
    );
    final String countString = countNumberFormat.format(count);

    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: 'Set: $countString',
      zero: 'Dropset',
    );
    return '$_temp0';
  }

  @override
  String get dropset => 'Dropset';

  @override
  String get create_goal_text => 'Create your first goal to get started';

  @override
  String get get_started => 'Get Started';

  @override
  String get enter_integer => 'Please enter a valid integer';

  @override
  String get enter_above_zero => 'Please enter a number above 0';

  @override
  String get unknown => 'unknown';

  @override
  String get sign_out_confirmation_message => 'Do you really want to sign out?';

  @override
  String get edit_profile_photo_title => 'Edit Profile Photo';

  @override
  String get delete_profile_photo => 'Delete Profile Photo';

  @override
  String get add_profile_photo => 'Add new Profile Photo';

  @override
  String get edit_training_plan_help_1_title => 'Name';

  @override
  String get edit_training_plan_help_1_message => 'You can change the name of your training plan: For example you can name it same as your training routine(e.g. \'push pull legs\').';

  @override
  String get edit_training_plan_help_2_title => 'Creating new trainings';

  @override
  String get edit_training_plan_help_2_message => 'To create a new training in your training plan, you can use the \'Add new\' button next to the days name.';

  @override
  String get edit_training_plan_help_3_title => 'Editing trainings';

  @override
  String get edit_training_plan_help_3_message => 'By clicking \'Edit\' on a training, you can edit its structure, add/remove exercises or rename the training.';

  @override
  String get edit_training_plan_help_4_title => 'Moving trainings';

  @override
  String get edit_training_plan_help_4_message => 'By dragging and dropping it on the correct day, you can move your training between the days of the week.';

  @override
  String get edit_training_title => 'Edit Training';

  @override
  String get error => 'Error';

  @override
  String get edit_training_plan_title => 'Edit Training Plan';

  @override
  String get enter_email => 'Enter your Email';

  @override
  String get enter_valid_email => 'Please enter a valid Email';

  @override
  String get check_inbox => 'Check your inbox';

  @override
  String get check_verification => 'Check Verification';

  @override
  String get send_again => 'Send again';

  @override
  String get password_label => 'Password:';

  @override
  String get sign_in => 'Sign in';

  @override
  String get or => 'or';

  @override
  String get percent => '%';

  @override
  String get other => 'Other';

  @override
  String started_at(String date) {
    return 'Started $date';
  }

  @override
  String get private_profile => 'Private Profile';

  @override
  String get empty_training_plan => 'Empty Training Plan';

  @override
  String get profile_not_found => 'Profile not found';

  @override
  String get training_not_found => 'Training not found';

  @override
  String decrease_value(String name) {
    return 'Drop $name';
  }

  @override
  String loading_title(String name) {
    return 'Loading $name...';
  }

  @override
  String get friends_status_requested_me => 'Accept Request';

  @override
  String get friends_status_requested => 'Requested';

  @override
  String get friends_status_none => 'Follow';

  @override
  String get friends_status_full => 'Followed';

  @override
  String increase_value(String name) {
    return 'Increase $name';
  }

  @override
  String get go_to_register => 'No Account? Create a new one.';

  @override
  String get enter_password => 'Enter your Password';

  @override
  String get password_requirements => 'Passwords cannot be empty and should be at least 6 characters long.';

  @override
  String get create_account => 'Create Account';

  @override
  String get enter_username => 'Enter your Username';

  @override
  String get username_requirements => 'Usernames cannot be empty';

  @override
  String get email_verification_title => 'Email not Verified';

  @override
  String get login_title => 'Login';

  @override
  String get register_title => 'Register';

  @override
  String get home_title => 'Home';

  @override
  String get okay => 'Okay';

  @override
  String get cancel => 'Cancel';

  @override
  String get invalid_input_title => 'Invalid Input';

  @override
  String get invalid_input_message => 'Your inputs are invalid. Please edit them and try again.';

  @override
  String get unsaved_title => 'Unsaved Changes';

  @override
  String get unsaved_message => 'You have unsaved Changes. Do you want to save them?';

  @override
  String get remove => 'Remove';

  @override
  String get delete_exercise_confirmation_title => 'Delete Exercise';

  @override
  String delete_exercise_confirmation_message(String name) {
    return 'Do you really want to delete the Exercise $name';
  }

  @override
  String get delete_training_confirmation_title => 'Delete Training';

  @override
  String delete_training_confirmation_message(String name) {
    return 'Do you really want to delete the Training $name from your Training Plan';
  }

  @override
  String get login_title_label => 'Please sign in to continue';

  @override
  String get register_title_label => 'Create an account to access the app';

  @override
  String get tutorial_welcome_title => 'Welcome';

  @override
  String get tutorial_welcome_message => 'Welcome to KeyPlan - your personal training planner. Let us introduce you to the app by giving you a short overview on the app!';

  @override
  String get tutorial_calendar_title => 'Calendar';

  @override
  String get tutorial_calendar_message => 'The tutorial starts here. This is also the opening point of the App. It is your training calendar. All your future trainings for the next seven days will be viewed here. Your calendar currently looks pretty empty. Let\'s fix that by editing your training plan!';

  @override
  String get tutorial_navigation_title => 'Navigation';

  @override
  String get tutorial_navigation_message => 'On the bottom of the app, you can find the main navigation menu. Here, you can navigate between the main components of the app. You can edit your training plan in your accounts settings. To go there, select the \'Account\'-Tab';

  @override
  String get tutorial_account_title => 'Account';

  @override
  String get tutorial_account_message => 'This is your account page. Here you can change your main account settings as your preferred set-rest duration etc. On the top, you can access the app settings. To get started with the app, you need to provide your personal training plan. To do so, scroll down to the section \'Training Plan\' and click on \'Edit\'.';

  @override
  String get tutorial_training_plan_edit_page_title => 'Editing Training Plans';

  @override
  String get tutorial_training_plan_edit_page_message => 'Now, the edit page of your training plan will be viewed. Your training plan provides information about how you train. You will provide your trainings for a specific day of the week and the training plan will put these trainings in the desired day of your calendar. For example, you can do a Push/Pull/Legs split and add Push to monday, Pull to wednesday and Legs to friday. Also, you can set your training plan\'s name.';

  @override
  String get tutorial_training_plan_create_training_title => 'Creating Trainings';

  @override
  String get tutorial_training_plan_create_training_message => 'Let\'s test this by creating a new training. To do so, click on the \'Add\'-button for the training section and select a day to add the training to.';

  @override
  String get tutorial_training_plan_click_training_title => 'Edit Trainings';

  @override
  String get tutorial_training_plan_click_training_message => 'Now, you see your training on the day, you added it to. To configure it, just click on it.';

  @override
  String get tutorial_training_plan_overview_title => 'Trainings';

  @override
  String get tutorial_training_plan_overview_message => 'The edit page of trainings works similar to the of the training plan. Trainings are part of a training plan and contain information about how a specific training will work. You can add exercises to it to do so. You can also edit the name of your trainings.';

  @override
  String get tutorial_add_exercise_title => 'Adding Exercises';

  @override
  String get tutorial_add_exercise_message => 'To add a new exercise, click on the \'Add\'-button of the exercises section. You can now expand the exercise and add a specific number of sets to it. Every set can have a unique amount of repetitions. Try it out and add a few exercises before continuing!';

  @override
  String get tutorial_save_training_and_plan_title => 'Saving';

  @override
  String get tutorial_save_training_and_plan_message => 'Now, after your training is fully configured, you can save. Be careful to always save your progress, your configuration won\'t be saved automatically to prevent unintentionally override of your training plan. On the bottom-right corner, you will see a button to save your training plan. Now, save your work!';

  @override
  String get tutorial_navigate_calendar_title => 'Back to Calendar';

  @override
  String get tutorial_navigate_calendar_message => 'You now created your personal training plan. Let\'s go back to your calendar by navigating to the \'Home\'-Tab';

  @override
  String get tutorial_click_calendar_training_title => 'Your Calendar';

  @override
  String get tutorial_click_calendar_training_message => 'After you edited your training plan, click on the refresh-button of your calendar, to sync your training plan with the calendar. The app will then insert your trainings into your calendar by inserting it into the day of the week, you selected. To get an overview on your training, just click on it!';

  @override
  String get tutorial_calendar_training_title => 'Training Preview';

  @override
  String get tutorial_calendar_training_message => 'This is the preview of a training. It will show you all the information as the duration of the training and it\'s exercises, so you can focus on your training.';

  @override
  String get tutorial_navigate_statistics_title => 'Statistics';

  @override
  String get tutorial_navigate_statistics_message => 'Let\'s start the final section of the tutorial. To do so, click on the \'Statistics\'-tab';

  @override
  String get tutorial_statistics_overview_title => 'Your Statistics';

  @override
  String get tutorial_statistics_overview_message => 'Here you can find your personal statistics. You can add your personal bests (aka. your personal records or PR\'s) to your statistics to never ever forgot your personal records and to easily track them.';

  @override
  String get tutorial_click_new_personal_record_title => 'Adding a new Personal Record';

  @override
  String get tutorial_click_new_personal_record_message => 'To insert a new personal record, you can just click on the \'Add\'-button on the bottom-right.';

  @override
  String get tutorial_create_personal_record_title => 'Adding a new Personal Record';

  @override
  String get tutorial_create_personal_record_message => 'A new page will pop up where you can configure your new personal record. You can differentiate between different types of personal records. Those are record-weights, record-lengths and record-times. You can also switch the unit of your personal record by clicking on the current unit. Now, insert the name of your personal record (e.g. \'Bench Press\'), enter the values and save it.';

  @override
  String get tutorial_edit_personal_record_title => 'Editing Personal Records';

  @override
  String get tutorial_edit_personal_record_message => 'Your personal record will now appear in your list. To edit or delete a personal record, just click on it!';

  @override
  String get tutorial_end_title => 'Tutorial Finished';

  @override
  String get tutorial_end_message => 'One last thing: If you have any questions, you can find on some points of the app on the top a question-mark, which explains features again to you if you forget. And that\'s it! You now have a basic understanding of the App and can enjoy your Fitness-Journey with Keyplan - Workout Planner. Have fun ;)';

  @override
  String get skip_tutorial => 'Skip Tutorial';

  @override
  String get start => 'Start';

  @override
  String get click_to_skip => 'Tap to view next step';

  @override
  String get next => 'Next step';

  @override
  String get error_no_connection => 'Could not connect to the server. Synching failed';

  @override
  String get error_authentication_internal => 'Something went wrong! Try later again or sign in again.';

  @override
  String get error_authentication_disabled => 'The authenticated account was disabled by an administrator. You will be signed out automatically';

  @override
  String get error_general => 'Something went wrong!';

  @override
  String get error_no_personal_record_selected => 'There is no Personal Record selected. Select one or create a new one, to be able to select it.';

  @override
  String get error_no_body_weight_values => 'You have no body weight values defined in the last month. To make your body weight your goal, you need to add a value to it first, so we can track it.';

  @override
  String get error_no_body_fat_values => 'You have no body fat values defined in the last month. To make your body fat your goal, you need to add a value to it first, so we can track it';

  @override
  String get error_too_many_personal_records => 'You can have a maximum of 20 Personal Records';

  @override
  String get invalid_trainings => 'The following trainings are invalid:';

  @override
  String get label_superset => 'Combine as superset with below:';

  @override
  String get your_body_stats_label => 'Body Stats:';

  @override
  String get now_label => 'Current:';

  @override
  String get selected_label => 'Selected:';

  @override
  String get create_body_value_title => 'Set todays Body Value';

  @override
  String get week => 'Week';

  @override
  String get month => 'Month';

  @override
  String get year => 'Year';

  @override
  String get add_today_value => 'Add value for today';

  @override
  String get loading => 'Loading';

  @override
  String get goal_finished_text => 'You\'ve just reached your next milestone and unlocked a new card. Don\'t forget to save it and share with your friends';

  @override
  String get goal_finished_title => 'Congratulations!';

  @override
  String get share => 'Share';

  @override
  String get go_back => 'Go back';

  @override
  String get search_email => 'Search Email';

  @override
  String get search => 'Search';

  @override
  String get search_account_instruction => 'To add a friend, type in the email of the account';

  @override
  String search_account_account_found(String email) {
    return 'The following account with the Email $email was found:';
  }

  @override
  String get copied_mail => 'Copied your mail to clipboard';
}
